# Build package and source zip on new tag push

name: Release from tag

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-[a-zA-Z]*'
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
    - uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Get tag name
      id: tag_name
      run: |
        echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
    - name: zip source
      run: zip -r discretesampling-${{ steps.tag_name.outputs.SOURCE_TAG }}.zip -x ".git/*" ".github/*" ".*" .
    - name: build package
      run: |
        python -m pip install --upgrade build && python -m build

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "discretesampling-*.zip,dist/discretesampling-*.whl,dist/discretesampling-*.tar.gz"